### ISSUE TITLE
eda.plot: box plot x-axis label is not clear

### ISSUE THREAD

**Issue by Waterpine** [sfu-db/dataprep#104]
Currently, when we use plot(df, x, y, bins), if you set the number of bins too large, the box plot's x-axis label is not clear.
<img width="580" alt="屏幕快照 2020-03-19 下午10 07 37" src="https://user-images.githubusercontent.com/29000790/77076233-8031ab00-6a2e-11ea-83ae-1d808737ca36.png">

**Comment by brandonlockhart** [comment]
@Waterpine I made the plot grow wider so the labels don't overlap
![Screenshot at 2020-03-19 15:10:17](https://user-images.githubusercontent.com/25874021/77119633-1694ab00-69f4-11ea-86b1-a7a7c0285bf3.png)
@jinglinpeng is this good for now? We should think about the format of the x axis labels for this plot at some point since they don't look good when the bin endpoints are large numbers or have lots of decimals.

**Comment by brandonlockhart** [comment]
@jinglinpeng According to the people at bokeh we cannot use the exact same xaxis tick situation that we used for the histograms (see https://discourse.bokeh.org/t/force-the-xaxis-to-be-linear-within-an-interval/5027).  I'm thinking of doing something similar for the boxplot where we only show 4 or 5 tick values on the xaxis. For example 
![Screen Shot 2020-03-29 at 12 56 32 PM](https://user-images.githubusercontent.com/25874021/77859207-e2bc4100-71bc-11ea-964b-942e09fbd32e.png)
The point for the xaxis here is to give a general idea of the range of values, and we show the exact interval in the tooltip. @jinglinpeng @Waterpine please let me know what you think

**Comment by jinglinpeng** [comment]
Thanks, it looks great!

**Comment by jnwang** [comment]
Shall we optimize ytics like we did for xrics, e.g., change it to 0.1M, 0.2M, .., 0.7M?

**Comment by brandonlockhart** [comment]
I optimized the ytics for all plots in PR #118 using the same formatting as the xtics. @jnwang @jinglinpeng please let me know any other problems with the formatting if you have any.
![Screen Shot 2020-03-30 at 1 06 39 PM](https://user-images.githubusercontent.com/25874021/77956958-97229980-7287-11ea-8190-8add6bb315d0.png)

**Comment by jnwang** [comment]
It looks great!

**Comment by Waterpine** [comment]
I am sorry for my delayed response. It looks great! Thanks!

**Comment by jinglinpeng** [comment]
I looks great! 

Another issue is that the parameter 'bins' is not consistent among the three plots. It seems only affects the box plot, while the scatter plot and the hexbin plot kept 5 bins. See the fig. below:
<img width="479" alt="Screen Shot 2020-03-30 at 8 58 03 PM" src="https://user-images.githubusercontent.com/18078770/77985608-c8bc5480-72c9-11ea-91b7-b74ec0cb7f86.png">

<img width="877" alt="Screen Shot 2020-03-30 at 9 02 57 PM" src="https://user-images.githubusercontent.com/18078770/77985644-e2f63280-72c9-11ea-8ed3-fd5d214895bc.png">

**Comment by brandonlockhart** [comment]
@jinglinpeng I don't understand what you mean by "scatter plot and hexbin plot kept 5 bins". We're not binning the values for the scatter plot, and the size of the hexbin plot hexagons are controlled by the parameter `tile_size`, so currently the `bins` parameter will only apply to the boxplot. If you mean the gridlines, I only added them since Tableau has them. Sorry if I'm misunderstanding you, can you please clarify how you expect the `bins` parameter to affect the scatter plot and hexbin plot?
