### ISSUE TITLE
Combine two function together

### ISSUE THREAD

**Issue by Waterpine** [sfu-db/dataprep#119]
I find that plot(df, x, y) and plot_correlation(df, x, y) have similar outputs. Why not combine them together. Then, we just use the plot(df, x, y) to analyze the data.
<img width="854" alt="屏幕快照 2020-04-02 下午9 32 53" src="https://user-images.githubusercontent.com/29000790/78255428-dff97d00-7529-11ea-891f-fbd912753e30.png">

**Comment by jinglinpeng** [comment]
There needs to be more thinking about the API design. Although the functionality has some redundancy, plot_correlation has something different from plot. For example, plot_correlation(df) shows the correlation matrix.

**Comment by Waterpine** [comment]
I mean we just combine plot(df, x, y) and plot_correlation(df, x, y) together. The main difference between the two functions is a regression line. There is no need to divide into two functions. Maybe we could output other figures when we use plot_correlation(df, x, y) function.

**Comment by dovahcrow** [comment]
The plots grouped under different "tasks" doesn't mean the plots from different tasks are not overlapping. 

One can always squeeze every plot into a single function, `plot`, to achieve minimal redundancy. As a result, you get pandas-profiling and every call to `plot` will take so long that exile us from interactive data analysis.

Our view of this problem is that we put plots required for a "task" under one function so that one can finish one EDA task by just one line of code. 

Go back to your question, yes the scatter plots are redundant but they are both useful in the "plot" task and in the "correlation" task.
