### ISSUE TITLE
eda: output lost in jupyter file

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#147]
**Describe the bug**
It seems I cannot save the output in jupyter notebook.

**To Reproduce**
run and save the following code as a notebook file:
`import pandas as pd`
`from dataprep.eda import plot`
`df = pd.read_csv("https://www.openml.org/data/get_csv/1595261/phpMawTba", na_values = [' ?'])`
`plot(df)`

Then reopen that notebook, the output fig. will be lost.

**Expected behavior**
It is expected to show the output fig. when reopen the jupyter file.

**Screenshots**
The output is lost when reopen the jupyter file. The screenshot is as follows:
<img width="1053" alt="Screen Shot 2020-04-30 at 3 38 31 PM" src="https://user-images.githubusercontent.com/18078770/80765798-c3387100-8af8-11ea-99cc-c8667c70b140.png">

**Comment by HRK777** [comment]
So I am facing exactly the same issue: An empty output is generated. 

However, I tested this issue & wanted to pin it down by running dateprep.eda from the command line and there it also doesn't show anything (neither with .show() nor with plt.show()) 

Before you ask, normal plots with Matplotlib worked fine

So this bug seems to be independent of Jupyter notebooks, at least for me... Did you try to run it somewhere else than on jupyter notebook? Maybe this bug is somehow also related to #102

**Comment by brandonlockhart** [comment]
Hi @HRK777, thank you for your comment on this issue. We think [the problem](https://github.com/sfu-db/dataprep/issues/102#issuecomment-647856819) is with one of our dependent libraries, Bokeh. Can you try clearing the cache before opening the notebook? This solves the problem for me in Chrome and Safari.
