### ISSUE TITLE
eda: supporting more types

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#160]
This issue is related to adding our own types. Suppose we want to add a type named 'text'. The idea is that:

1. Suppose we define the new types in `eda.dtype`, then add 'text' type to `eda.dtype`.

2. We allow users input the column type when s/he calls the plot. The idea is from the dtype parameter in [`pd.read_csv`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Suppose user wants to analyze a text column 'comment', s/he could call `plot(df, "comment", dtype = {"comment": eda.dtype.text})` to let eda knows the 'comment' column should be regarded as 'text'.

3. The type information is stored in a type dict. The key is the column name and the value is the type. E.g., `dict['comment'] = eda.dtype.text`.

3. For the column whose type is not given by the user, we have an adapter to transform the original type of df to our own type. For example, suppose column A is datetime64 in df, then the adapter will transform it to our own type 'date', and add the information to the type dict. I.e., `dict['A'] = eda.dtype.date`.

4. Now we can start do the plotting. All the processing that relies on column type will use the type dict. to get the type information.

In the above design, the type information is decoupled with the dataframe, which may not be good. Not sure whether we could define our dataframe to contain the type information.

Another thing needs to be noticed is that if we make this change, it will affect many functions, as they all made the plots based on the column type.

**Comment by jnwang** [comment]
We need to have a clear definition of data types. Maybe create a new issue for it?


**This is what people use for statistical analysis.** 

<img width="594" alt="Screen Shot 2020-05-16 at 2 25 38 PM" src="https://user-images.githubusercontent.com/1028970/82130567-58866700-9781-11ea-8283-7e615424b767.png">


**This is what people use for data management.** 
![MySQL-Data-Types](https://user-images.githubusercontent.com/1028970/82130617-c599fc80-9781-11ea-98ed-a35f060efc0f.jpg)

**Some work studies semantic type, which is good for automated data cleaning, schema matching, and data discovery. Here is one example from https://arxiv.org/pdf/1905.10688.pdf**

<img width="352" alt="Screen Shot 2020-05-16 at 3 06 03 PM" src="https://user-images.githubusercontent.com/1028970/82131123-ca14e400-9786-11ea-8c66-cffbbbfa9c9f.png">

**Comment by dovahcrow** [comment]
I totally agree with the idea of semantic types: this is the one of the key steps to make our library more intelligent.

The way I imaging to implement the auto type is that first, we should have the type tree. At the first two layers, we have the exact "syntactic types" like:
![image](https://user-images.githubusercontent.com/998606/82132565-e9673d80-9795-11ea-8d1d-4f2ff524a810.png). After that, under each leaf node of the syntactic type tree, there will be a semantic type subtree. E.g. "Sex" is under the Nominal node.
Secondly, as long as we have the tree, there are several technical challenges:
1. the first technical challenge is to have a function `detect` that takes as input a column of data and outputs a node of the type tree. `detect` should also using sampling or other methods to make the detection faster. This part should already have a bunch of papers.
2. the second technical challenge is due to the sampling nature of 1, the dtype of the column is not deterministic. After the initial dtypes is decided by `detect` function, we do calculations. But it is likely that the initial type detection is not correct so we should have a way to efficiently fall back and re-detect when doing the computation. This brings in complexities to the implementation.

The `detect` function can be one of the component of the "plot-ready-dataframe" module.

**Comment by brandonlockhart** [comment]
I also like the idea of semantic types and automatically detecting them as Young proposed. I'll just add that I think we should also provide a way for the user to specify the semantic type in case we detect the type incorrectly.

**Comment by jinglinpeng** [comment]
@jnwang  @dovahcrow @brandonlockhart  I also agree with the semantic types. As the main reason of defining different types is that we want to process them differently (e.g., generate different plot), we may define types progressively: whenever we want to process a type differently, we define a type. E.g., we now want to plot text differently from categorical type, we claim a type named 'text'.

I also like the type inference idea, but this part could be very complex. We may do it later. The current solution is that:
1. User can directly input the type information (see point 2 in my proposal).
2. For the column whose type is unclear, we use its dataframe type (see point 4).

In the future, we could add the type inference functionality into this solution by inferring the type of columns whose type is not specified by the user.
