### ISSUE TITLE
eda.plot: allow user to specify column types

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#161]
This is a more specific task description as a starting point towards issue #160:

1. Define 'Categorical', 'Numerical', 'DateTime', 'Text', ...(see issue #160), in eda.dtypes.

2. Add a parameter 'dtype' in `eda.plot`, which allows user to specific the column type. E.g., `plot(df, dtype = {"comment": eda.dtype.Text, "sex": eda.dtype.Categorical})` specifies the 'comment' as text and "sex" as categorical.

3. Add a function `detect_dtype(column, known_dtypes)` in `eda.dtype` to detect the type of the column. The `known_dtypes` is the `dtype` parameter given by the user. This function will return the type of the column. If the column is in `known_dtypes`, then it returns the column type from `known_dtypes`. Otherwise, it transforms the column's dataframe type into 'Categorical', 'Numerical', 'DateTime' or 'Text'. This function could be improved in the future.

4. Add a function `is_dtype(a: DType)` in `eda.dtypes.DType`. It returns True if the current dtype is the same as `a`.

5. Change the type detection part (e.g., `if is_numerical(df[col].dtype)` ) with `detect_dtype`.

For a testing, the following code should show a bar chart for `pclass` column:
`import pandas as pd`
`from dataprep.eda import *`
`df = pd.read_csv('https://www.openml.org/data/get_csv/16826755/phpMYEkMl')`
`plot(df, dtype = {"pclass": eda.dtype.Categorical})`

**Comment by dovahcrow** [comment]
I think we should prioritize this task before other tasks

**Comment by dovahcrow** [comment]
# DType Tree Design

First we define the dtype tree:
```python
class DType:
    pass
class Categorical(DType):
    pass
class Nominal(Categorical):
    pass
...
```

# By instance vs By class

Consider in `plot` we allow a user to specify the column dtype: `plot(..., dtype={"A": <some type>}`.
There are two ways to specify the dtype: 1. by class e.g. `{ "A": Nominal }`, 2. by instance, a.k.a. `{ "A": Nominal() }`.

The second one has two benefits and 1 drawback:
1. Sometimes a type can carry parameters. There's no way to carry that information using the "by class" approach.
2. It is easier to work with the typing system.

However, the drawback is that it is not convenient and weird to specify `{"A": Nominal()}` as compare to `{"A": Nominal}`. But this can be solved using an additional normalization process.

Here the proposal suggests using the "by instance" way across the whole library, and having an additional normalization procedure to normalize the user input so that our functions accept all of `dtype={"A": "nominal"}`, `dtype={"A": Nominal}` and `dtype={"A": Nominal()}`.

# Functions required to be implemented

`def detect_dtype(col: dd.Series) -> DType`: this function detects the dtype of a specific column and return its type in our type system, by instance.
`def isdtype(dtype1: DType, dtype2: DType) -> bool`: this function detects if dtype2 is dtype1. Note: `istype(Nominal(), Categorical())` should be `true`!
`def normalize_dtype(dtype_repr: Any) -> DType`: this function normalizes a dtype repr, e.g. a string or a class into the corresponding dtype instance.

# Usage of the functions

When entering a plot function, the type system should do these jobs:
1. call `normalize_dtype` to normalize user input dtypes, if specified.
2. call `detect_dtype` on each of the columns that their dtypes are not specified by the user.
3. create a dtype dict `dtype_info` which contains dtypes for all the columns.

With dtype dict given, whenever there are dtype-dependent plotting tasks, call `isdtype` to branch the code.

**Comment by dylanzxc** [comment]
In our type tree, DateTime is the child of Numerical. Therefore is_dtype(DateTime, Numerical) will return True and cause a lot of errors in compute() and render(). Can we get rid of DateTime from Numerical for now? And I'm wondering what is the reason for us to keep DateTime under Numerical?

**Comment by jinglinpeng** [comment]
@dylanzxc Could we use `is_dtype(DateTime, Continuous)` and `is_dtype(DateTime, Nominal)` to replace `Numerical` and `Categorical`?
