### ISSUE TITLE
Enhance eda.plot_missing: add heatmap and dendrogram

### ISSUE THREAD

**Issue by Waterpine** [sfu-db/dataprep#168]
**Task**: add heatmap and dendrogram to the plot_missing(df) function.

My proposal is to add another tab with the heatmap and dendrogram like we have different methods to calculate the correlation between two columns. However, the main difference between dataprep and pandas-profiling is that we only have three tabs: count+matrix, heatmap, and dendrogram. (The examples of pandas-profiling could provide us with some references https://github.com/pandas-profiling/pandas-profiling)

As for automatically marking missing values, I think we could directly utilize the NumPy or Pandas and Dask library.

Do you have any other comments? @Sanjana12111994 @dovahcrow @jinglinpeng @jnwang

**Comment by jnwang** [comment]
Looks good!

For automatically marking missing values, we need to define a list of values and assume that they are missing values by default rather than using df.notnull(). For example, if it is an empty string, it should be treated as a missing value. 

I would suggest also taking a look at https://github.com/ResidentMario/missingno. For example, we can add a tag named **bar chart** like missingno. Another point that we can learn is its advanced configuration: https://github.com/ResidentMario/missingno/blob/master/CONFIGURATION.md. 

This issue seems a bit large to me. Should we split it into multiple issues? 

Task 1. Automatically marking missing values
Task 2. Bar Chart
Task 3. Heatmap
Task 4. Dendrogram

**Comment by Waterpine** [comment]
I think the bar chart of missingno is similar to the count of pandas profiling. We could add a tag named **bar chart** or **count**. Moreover, I agree with you. We could split it into 4 tasks.

**Comment by dovahcrow** [comment]
I think there is only Task 4. Dendrogram left.
