### ISSUE TITLE
plot stops working if variable is passed as second argument

### ISSUE THREAD

**Issue by andrealorenzon** [sfu-db/dataprep#217]
**Describe the bug**
as per topic, in Jupyter Notebook. Happened first while looping through a list of column names.

**To Reproduce**

```python
df = pd.DataFrame(...)
var = 'column1'
plot(df, 'columns1') # works
plot(df, var) # breaks something
plot(df. 'columns1') # does not work anymore, even in other blocks.
```

**Expected behavior**
I expected the plot to show.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Mint linux
 - Browser : Firefox
 - Platform Jupyter Notebook
 - Platform Version: n/a
 - Python Version 3.7.2
 - Dataprep Version last one at July 6th

**Additional context**

If I restart the kernel and the notebook, it starts working again.

**Comment by brandonlockhart** [comment]
Hi @andrealorenzon, thanks for raising this issue! I cannot reproduce it in Safari. Could you please provide some minimal sample data that causes the issue?

I will also add that you need to call `show()` like `plot(df, 'column1').show()`, if `plot()` is not the last value in a cell. But since you said `plot(df, 'columns1')` does not work anymore, even in other blocks, I don't think this your problem.

Is it the case that the plots aren't rendering and there's no output error in Jupyter? Could you please check the Console output to see if there are any clues. If not, I'm not sure what is causing this problem. @dovahcrow do you have any ideas?

**Comment by andrealorenzon** [comment]
Sadly, no, the dataset i'm studying is under NDA.

**Comment by jinglinpeng** [comment]
Hi @andrealorenzon , I cannot reproduce the error. Could you give us a simulation dataframe, which has the same schema (column number and column types) of your data? We could try to reproduce it in the simulated data.

**Comment by andrealorenzon** [comment]
I used the GUSTO dataset, CSV format. 
https://www.kaggle.com/c/gusto

this is the code that doesn't work.

```python

from dataprep.eda import plot

for var in df.columns:
    plot(df[[var]])
```

**Comment by jinglinpeng** [comment]
Hi @andrealorenzon , we do not support column as the input. Could you try `plot(df).show()` or `plot(df, var).show()` instead? (`var` should be in string type)

**Comment by dovahcrow** [comment]
Closed due to inactivity.
