### ISSUE TITLE
parameter management for `plot`: stage 1

### ISSUE THREAD

**Issue by jinglinpeng** [sfu-db/dataprep#243]
**Is your feature request related to a problem? Please describe.**
This is a detailed task related to issue #238 

As an initial stage, we first work on `plot`. We create an API `_plot`, with following example function calls:
```python
_plot(df, 
    x, 
    dtype = {"x": Categorical}, 
    display = "auto", 
    config = {"hist.bins": 10, "hist.width": "auto", "hist.height": "auto"})

_plot(df, 
    x, 
    dtype = {"x": Categorical()}, 
    display = "auto", 
    config = [Histogram(bins=10,width="auto", height="auto")])
```

This API is an adapter of the current `plot` function. It extracts the parameters needed by the current `plot` function and then calls the current `plot` function. In the next stage, we will replace the old `plot` function with this new `_plot`.

The task includes:

1. Create configuration classes such as `Histogram`,  `BarChart`, `WordCloud`, .... in `dataprep/eda/basic/configs.py`, each class has related attributes from the old `plot` (https://sfu-db.github.io/dataprep/dataprep.eda.html). For example, `bins` should be an attribute in `Histogram`:
```python
@dataclass
class Histogram:
    bins: int = 10
```
, and `top_words` should be an attribute in `WordCloud`. Each attribute has a default value as in the current `plot` function.

2. Each class can set attribute by a dict. For example, `Histogram.from_dict({"bins": 10, "width": 100})` will set the `bins` attribute as 10 and `width` attribute as 100. This can be done by
```python
@dataclass
class Histogram:
    bins: int = 10
    @classmethod
    def from_dict(cls, dict):
        return cls(**dict)
```

3. Each class also contains the canonical name for the tab.
```python
@dataclass
class Histogram:
    @property
    def name(self):
        return "Histogram"
```
so that this can be used in the `plot` function for naming.

4. In `_plot` we will build the related configuration object from the input `config` parameter. For example, `_plot(..., config = {"hist.bins": 10, "word_cloud.top_word": 20})` will build a `Histogram` and `WordCloud` and set related their attributes based on the input.

5. In this stage, we just extract the related attributes from step 3 and get the parameter for the current `plot`. For example, we extract `top_word` from `WordCloudConfig`, and the pass the `top_word` to current `plot`. In this way, we get all the parameters for the current `plot`, and then we directly call it.

I would suggest making common functions as a base class for other configuration classes to inherit. e.g. the from_dict method and the name method can be put into the base class as a interface.

**Comment by jinglinpeng** [comment]
@Waterpine  Could you estimate the points for this task? I think you could just choose a few fig types to work on, such as the hist and bar chart, such that this task could be finished by next milestone(7.26). Please also consider the time for writing docstring and testing.

**Comment by Waterpine** [comment]
@jinglinpeng I think the first step is to create a histogram class first. If I could finish the first class, then it is not difficult for me to create other classes.

**Comment by brandonlockhart** [comment]
@jinglinpeng and I want to define what components of `plot(df)` the user can configure in the `display` parameter. We propose the user be able to specify whether or not to show 
1. each plot type (histogram and bar chart),
2. the statistics (so all or no statistics),
3. the insights. 

By, default, `display` will be `display=["histogram", barchart", "statistics", "insights"]`. Whenever "insights" is in the `display` list, we will compute all the insights we have for `plot(df)` and show them all in the insights tab. The relevant insights will also be distributed to any other component in `display`. For example, if the user specifies `plot(df, display=["histogram", "insights"])`, we will compute all insights (even for categorical columns and stats) and show them all in the insights tab, and distribute the relevant insights associated with numerical columns to the histograms.
Moreover, we think the user may not want to compute all the insights. We propose allowing the user to specify the insight type in `display`. For example, `plot(df, display=["histogram", "insight.skew"])` to compute only the skew insight.
Please let us know if you have any comments about this.

**Comment by jnwang** [comment]
Thanks for proposing this design. I don't see any issue with it.

**Comment by brandonlockhart** [comment]
@dylanzxc @jinglinpeng and I want to move forward with this design but first clarify some details. Since we create a configuration class for each plot type, this raises the problem that different functions generate the same plot type and require different parameters. For example, `plot(df, numerical, numerical)` and `plot(df, numerical, categorical)` each output a boxplot; in the former, `bins` can be set, and in the latter, `ngroups` can be set. But we propose a class with all possible attributes

``` python
class BoxPlot:
    bins: int = 50
    ngroups: int = 50
    ...
```

In the documentation, we will make it clear which parameters are relevant to each function. In the how-to guide, we will only show parameters relevant to the function, eg the `plot(df, numerical, numerical)` box plot how-to guide will show `bins` and not `ngroups`.

Another possibility is to have a class for each plot and data type, eg BoxPlotNumerical, BoxPlotCategorical. But for a line chart, we would already have four different classes, and so we prefer the above approach.

### Global parameters
We plan to have a few "global" parameters to make some common parameters easy to set. For example, the global parameter `bins` will function as `plot(df, x, bins=20)= plot(df, x, config={"hist.bins": 20, "kde.bins": 20})`. Other global parameters include `height` and `width`.

Please let us know any comments.

**Comment by jnwang** [comment]
I like this proposal due to its simplicity. 

I want to see how well this design is in terms of extensibility? For example, can you illustrate how to add a new plot (eg, violin plot) to dataprep.eda with this design?

**Comment by jinglinpeng** [comment]
> I like this proposal due to its simplicity.
> 
> I want to see how well this design is in terms of extensibility? For example, can you illustrate how to add a new plot (eg, violin plot) to dataprep.eda with this design?

In this design, adding a new plot would be easy, as most params are local, except for render-related params like `height` and `width`. When adding a new plot, we create a config class of that plot, and then add related params in the config class.

**Comment by dylanzxc** [comment]
There are two problems that need your final decision:

1. In plot(df, x), the insights are attached to corresponding plots instead of showing in an overview section. For example uniform and normal insights are shown with histogram only. Then there comes the problem if the user input is plot(df,x, display=["insight.uniform", "insight.normal", "bar", "wordcloud"]). They don't want to show histogram but they want the insights which can only be shown with the histogram tab.  In plot(df), as we have an overview section for all the insights it won't be a problem there. But we assume users will use the same display list for other functions(plot(df,x)) which will cause the above problem.

2.  A more specific problem associated with the above one is, in plot(df, x) some insights(zeros, negatives, skewness, unique..) are attached to STATS tab. Instead of showing the sentences, we use the highlight(this is a decision made in a previous UI meeting). 
![image](https://user-images.githubusercontent.com/56427336/95669260-98385b80-0b33-11eb-875d-f39823c5f50c.png)
Then the problem here is if the user doesn't want an insight, are we gonna turn off the corresponding highlight? Do we also need to delete(not compute) that information from stats tab? Currently, we keep the stats tab fixed. 

Jinglin, Brandon, and I had a meeting to discuss today. Please add on the info I missed @jinglinpeng @brandonlockhart 
Your final decisions are important. @jnwang @dovahcrow

**Comment by jnwang** [comment]
Thanks @dylanzxc for posting these questions.

For 1, do you think the following scenario is common? 
> Moreover, we think the user may not want to compute all the insights.

I guess in most cases, users want to see all insights. In other cases, users may want to disable all insights when sharing a notebook. The scenario that users want to show some of the insights may not be common.

If this is the case, then we only allow users to specify "insights" in the display rather than specify certain types of insights like "insight.uniform", "insight.normal".

For 2, I want to understand how hard it is to implement the following. If it is hard, then I am ok to keep the stats tab fixed. 

- display = ["statistics", "insights"] show all stats with highlights (i.e., the figure you show above).
- display = ["statistics"] show all stats without highlights (i.e., "Distinct Count", "Missing", and "Missing (%)" are in black rather than in red).
