### ISSUE TITLE
create_report function should also take in a 'path' variable where the report is to be written to

### ISSUE THREAD

**Issue by stillbreeze** [sfu-db/dataprep#270]
**Is your feature request related to a problem? Please describe.**
The `create_report` method hardcodes the path where the report is written to the current working directory which is not ideal.

**Describe the solution you'd like**
Simplest solution is to add a `filepath` variable to the `create_report` function input which denotes the path where the report is to be written.

**Describe alternatives you've considered**
NA

**Additional context**
The method in question: https://github.com/sfu-db/dataprep/blob/develop/dataprep/eda/create_report/__init__.py#L19-L51

**Comment by brandonlockhart** [comment]
Hi @stillbreeze, thanks for your feature request! Our `create_report` feature is very new, and we will actually change the functionality slightly in the next release which will include your desired feature:
We will show the report in the notebook with
```python
report = create_report(df)
report
```
The report can then be saved with
``` python
report.save(to="file")
```
where `"file"` is the name or path of the file to generate including the extension .html.

**Comment by eutialia** [comment]
I want to add some notes to the last comment:

1. You can also see the report by calling `create_report(df)` directly.

2. The current design is to separate filename and path, which may be helpful to some users (e.g., batch generation).
For example:
``` python
report.save(filename='my_report', to='~/Document')
```
If nothing is passed to this method, the report will be saved to current woking directory as 'report.html'. Also you don't need to specify the file extension because we only support HTML report at the moment.
