### ISSUE TITLE
clean_country designing

### ISSUE THREAD

**Issue by dovahcrow** [sfu-db/dataprep#357]

**Comment by ryanwdale** [comment]
### API

From [Brandon's design](https://github.com/brandonlockhart/dataprep_cleaning_api/blob/master/clean_country.ipynb)
 
Follow the [ISO 3166 country codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes),

Convert a country name into the following formats:,
     1. "name": the country name,
     2. "official": the official state name,
     3. "alpha-2": two letter abbreviation,
     4. "alpha-3": three letter abbreviation,
     5. "numeric": numeric code

```python 
def clean_country(
    df: Union[pd.DataFrame, dd.DataFrame],
    column: str,
    input_format: Union["auto", "name", "official", "alpha-2", "alpha-3", "numeric"],
    output_format: Union["name", "official", "alpha-2", "alpha-3", "numeric"],
) -> pd.DataFrame:

def validate_country(
    x: Union[str, int, pd.Series],
    input_format: Union["auto", "name", "official", "alpha-2", "alpha-3", "numeric"],
) -> Union[bool, pd.Series]:
```

###  Matching "name" and "official" input formats

Continuation of discussion [here](https://github.com/sfu-db/dataprep/issues/347)

My plan is to use regexes from the country_converter project https://github.com/konstantinstadler/country_converter/blob/master/country_converter/country_data.tsv.

I'll adjust the regexes to make them slightly more strict. Some of the regexes use shortened versions of the country name which I'll change to the full name ie afghan -> afghanistan. The regexes also match an arbitrary string in between multi word names in some cases, I plan to change that to just a single space. For example if a country name is "Foo Bar", often times the country converter library uses the regex "foo.*bar" which I would change to "foo bar" (could also change it to "foo.?bar" which is also used a lot in the country_converter.).

Then regex.search will be used on these regexes to look for a match.

Also I plan to add an optional parameter `fuzzyDist` (default 0) like in this library https://www.rdocumentation.org/packages/rangeBuilder/versions/1.5/topics/standardizeCountry. If set to a non zero value the edit distance between the two strings will also be checked, if the edit distance is less than fuzzyDist it's a match.

Example regexes and country names:

"canada", "Canada"
"^(?!.*south).*georgia", "Georgia"
"channel island", "Channel Island"
"^(?!.\*north.\*).*ireland", "Ireland"

Example inputs and outputs:

"canada" -> "Canada"
"the country canada is nice" -> "Canada"
"cnada" -> "no match"
"cnada", `fuzzyDist` = 1 -> "Canada"
"channel island" -> "Channel Island"
"channel foo island" -> "no match"
"foo georgia bar" -> "Georgia"
"south georgia" -> "no match" (South Georgia is an island unrelated to Georgia the country)
" ireland " -> "Ireland"
"northern ireland" -> "no match" (Northern Ireland is part of the United Kingdom)
"canada united states" -> "Canada" (When an input contains multiple matches the first occurring match in the string will be returned)

Results will be cached to save time since a data set may have many duplicate countries in a column.


### Matching "alpha-2", "alpha-3" and "numeric" input formats

My plan for these formats is to look for a direct match.

Example inputs and outputs:

"CA" -> "Canada"
" CA " -> no match
"124" -> "Canada"
124 -> "Canada"
"country:  CA" -> "no match"

Because these are more standardized formats I believe they would be less likely to appear in messy data. Also, due to the short length of these inputs there would be greater potential for false matches if the same method was used as the "name" and "official" formats was used. 


### Further Ideas/Problems

Handling cases such as "the country canada is nice" and " Ireland " is inconsistent with the `clean_lat_long` function (see [#310](https://github.com/sfu-db/dataprep/pull/310)). However, to not handle these cases while retaining functionality we would need to define a set of strings we would recognize as being a valid country, eg including "China", "PRC", "People's Republic of China", "The People's Republic of China", "People's Rep. of China", ..., which could be tedious to create.

Should `validate_country("the country is canada it is nice")` return true? In the meeting most people thought it should return false. However, having `validate_country` return false on input that `clean_country` successfully cleans is inconsistent with the `clean_lat_long` API. 

One idea is to have an additional function `transform_country` which would clean data as described above. The `clean_country` function could then have consistent behaviour with `clean_lat_long`, converting countries between formats and not handling cases such as  "the country canada is nice" and " Ireland ".

Another solution is to add an optional parameter `strict` to the `clean_country` and `validate_country` functions. When `strict = True` then the input must match the ISO 3166 country code format exactly to be cleaned or validated (similar behaviour to `clean_lat_long`). If `strict = False` `clean_country` works as described above and `validate_country` returns True when `clean_country` successfully cleans the input. 

Examples:

`clean_country`
" the country canada is nice", `strict = False` -> "Canada"
" the country canada is nice", `strict = True` -> "no match"
"canada", `strict = True` -> "Canada"
" canada ", `strict = True` -> "no match"

`validate country`
" the country canada is nice", `strict = False` -> True
" the country canada is nice", `strict = True` -> False
"canada", `strict = True` -> True
" canada ", `strict = True` -> False


Any input is appreciated!

**Comment by brandonlockhart** [comment]
Great job, Ryan! This is really well written. My comments:

> Matching "alpha-2", "alpha-3" and "numeric" input formats
> My plan for these formats is to look for a direct match.

I like this approach. However, I would also be open to stripping leading and trailing whitespace, especially if we find a dataset in the wild where this would be useful.

> One idea is to have an additional function transform_country which would clean data as described above. The clean_country function could then have consistent behaviour with clean_lat_long, converting countries between formats and not handling cases such as "the country canada is nice" and " Ireland ".

I like the idea of separating cleaning and converting/standardizing, particularly if this is appropriate for other APIs as well. But for the function names, I think it's confusing if `transform_country` does the cleaning and `clean_country` does the conversion between formats.

I also like the `strict` parameter. But I wonder how often countries are stored in the ISO 3166 format; users may often have to set `strict=False` if there are many false negatives in `validate_country`. I think we should look at some real-world datasets to determine the prevalence of this format. Also, with respect to consistency across the cleaning functions, this parameter may only be applicable to semantic types with a well-defined format. For example, it's not clear to me how this parameter would work for `clean_phone` because there are many possible formats for a phone number.

So, my preference at this point is not to create the function `transform_country`, but to instead do regex search or direct match as you described for the respective formats in `clean_country`. I also prefer to add the parameter `strict` to `validate_country` with default `True`. I see the argument for adding strict to `clean_country` also, but I think if we add it to `clean_country` the default should be `False`.

I'm curious what @yxie66 and others think.

Also @ryanwdale, did we confirm that `clean_country("canada usa, china")` will return the first match, so Canada?

**Comment by ryanwdale** [comment]
Thanks for the feedback, Brandon! 

I agree with all your points and I like your preferred approach. 

> But I wonder how often countries are stored in the ISO 3166 format; users may often have to set strict=False if there are many false negatives in validate_country. I think we should look at some real-world datasets to determine the prevalence of this format.

I'll start looking into some real-world datasets.

> Also @ryanwdale, did we confirm that if we use regex.search, clean_country("canada usa, china") will match and convert the first country in the string, so it would return "Canada"?

Ya I checked this and it works as expected.

**Comment by yxie66** [comment]
Thank you, so far it looks very cool @brandonlockhart @ryanwdale . I have a few things to discuss.

1. Overall I like the current plan, which is to focus on `clean_country` with `fuzzydict `parameter. I think it is able to provide users with enough flexibility. 

2. For `strict` parameter I agree that it should be set to `False` as default for `clean_country` while `True` for `validate_country`. Do you guys think it's necessary to implement something like `extract_country` and expose it to users? When `strict` is set to `False` then this function is guaranteed to return a valid country entity.

3. When there are multiple country entities detected in text, do you think it's necessary for us to provide an alternative to return a list of all countries, or something similar?

4. For real datasets I found some user case like https://stats.stackexchange.com/questions/25435/how-to-classify-country-names-given-possible-alternate-spellings-or-abbreviation. In those cases inconsistency always come from user typing. It would be ideal to find a comprehensive dataset with a dirty country column, though.

**Comment by brandonlockhart** [comment]
Thanks @yxie66 for your comments. I don't understand this function however
> Do you guys think it's necessary to implement something like extract_country and expose it to users? When strict is set to False then this function is guaranteed to return a valid country entity.

I don't understand how we can guarantee that we will return a valid country. Can you please elaborate on this?

For 3., I don't think we should do this now unless we find a real-world use case where it's needed. I think in most cases `clean_country` will be used to standardize and transform countries. If we add this functionality, I think we would need to justify why we don't have it in all of our cleaning functions. This is just my opinion. What do you think @yxie66?

**Comment by jnwang** [comment]
Excellent job! You can find real world datasets from https://datasetsearch.research.google.com/

**Comment by yxie66** [comment]
> Thanks @yxie66 for your comments. I don't understand this function however
> 
> > Do you guys think it's necessary to implement something like extract_country and expose it to users? When strict is set to False then this function is guaranteed to return a valid country entity.
> 
> I don't understand how we can guarantee that we will return a valid country. Can you please elaborate on this?

Sorry for confusion here, what I meant is that when strict is set to False and a valid country entity can be parsed from input text (which can be messy), it will be returned. Otherwise, it will return nothing. When strict is set False, it will be called. Do you think we should expose it to users as well?

**Comment by brandonlockhart** [comment]
Thanks, @yxie66 for clarifying. I think we could. In my opinion, we don't need to do this now as I'm unsure about the prevalence of this task. How do you justify needing this functionality for this semantic type and not others?
