### ISSUE TITLE
regex for international phone numbers for `clean_phone()`

### ISSUE THREAD

**Issue by brandonlockhart** [sfu-db/dataprep#370]
With Canadian and American phone numbers completed in #354, we need to create a regex for [international phone formats](https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers). Some resources to help get started are [this](https://stackoverflow.com/questions/2113908/what-regular-expression-will-match-valid-international-phone-numbers) StackOverflow post and the phonenumbers library [code](https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/phonenumbers/phonenumberutil.py).

**Comment by atol** [comment]
Here is a first draft of a proposed Regex, based on [this  post](https://stackoverflow.com/questions/47568171/regex-improvements-for-international-common-and-rf3966-phone-number-validation) on Stack Overflow.

```^(?=(?:\(?(?:\+|00))?(?:(?:[\(\-\)\.\/ \t]*\d){7,10})?(?:[\-\.\/ \t]?\d{2,3})(?:[\- \t]?(?:#|x|ext|extension)[\-\.\:\/]?[ \t]?\d{1,4})?$)(?:\(?(?:\+|00)(297|93|244|1264|358|355|376|971|54|374|1684|1268|61|43|994|257|32|229|226|880|359|973|1242|387|590|375|501|1441|591|55|1246|673|975|267|236|1|61|41|56|86|225|237|243|242|682|57|269|238|506|53|5999|61|1345|357|420|49|253|1767|45|1809|1829|1849|213|593|20|291|212|34|372|251|358|679|500|33|298|691|241|44|995|44|233|350|224|590|220|245|240|30|1473|299|502|594|1671|592|852|504|385|509|36|62|44|91|246|353|98|964|354|972|39|1876|44|962|81|76|77|254|996|855|686|1869|82|383|965|856|961|231|218|1758|423|94|266|370|352|371|853|590|212|377|373|261|960|52|692|389|223|356|95|382|976|1670|258|222|1664|596|230|265|60|262|264|687|227|672|234|505|683|31|47|977|674|64|968|92|507|64|51|63|680|675|48|1787|1939|850|351|595|970|689|974|262|40|7|250|966|249|221|65|500|4779|677|232|503|378|252|508|381|211|239|597|421|386|46|268|1721|248|963|1649|235|228|66|992|690|993|670|676|1868|216|90|688|886|255|256|380|598|1|998|3906698|379|1784|58|1284|1340|84|678|681|685|967|27|260|263))?(?:[\)\-\.\/]?[ \t]?)(\(0\d[ ]?\d{0,4}\)|\(\d{1,4}\)|\d{0,4})((?:[\-\.\/ \t]{0,2}\d){3,8})(?:[\- \t]?(?:#|x|ext|extension)[\-\.\:\/]?[ \t]?(\d{1,4}))?$```

The explanation is set out below:

* `^` - Start of expression.
* `(?=(?:\(?(?:\+|00))?(?:(?:[\(\-\)\.\/ \t]*\d){7,10})?(?:[\-\.\/ \t]?\d{2,3})(?:[\- \t]?(?:#|x|ext|extension)[\-\.\:\/]?[ \t]?\d{1,4})?$)` - Positive lookahead (asserts that the below Regex matches). Basically checks to see if the number is a possible phone number.
    * `(?:\+|00))?` - Non-capturing group. Matches the `+` character or `00` digits between zero and one times.
    * `(?:(?:[\(\-\)\.\/ \t]*\d){7,10})?` - Non-capturing group. Optionally matches between 7 and 10 digits separated by one or more spaces, tabs and/or the characters `(`, `-`, `)`, `.`, `/`.
    * `(?:[\-\.\/ \t]?\d{2,3})` - Non-capturing group. Matches two or three digits in a row, with an optional leading space, tab or `(`, `-`, `)`, `.`, `/` character.
    * `(?:[\- \t]?(?:#|x|ext|extension)[\-\.\:\/]?[ \t]?\d{1,4})?`- Non-capturing group. Optionally matches the `x`, `ext` or `extension` characters followed by 1-4 digits. The characters may be preceded by a space or tab. The digits may be preceded by one of the characters `-`, `.`, `\`, `#` followed by a space or tab.

    If the above Regex matches, then we attempt to separate the different components of the phone number using capturing groups.

* `\(?` - Optional open bracket `(`.
* `(?:\+|00)` - Non-capturing group. Matches the `+` character or `00` digits.
* `(297|93|...|260|263)?` - 1st capturing group. Optionally matches one of the country codes from the [simple-country-dial-codes](https://github.com/xxxdepy/simple-country-dial-codes/blob/master/country-calling-codes.json) GitHub repo. All the country codes are included in the Regex for the sake of the demo (linked below), but the actual implementation could use the JSON file.
* `(?:[\)\-\.\/]?[ \t]?)` - Non-capturing group. Matches a space, tab or `)`, `-`, `.`, `/` character between zero and one times.
* `(\(0\d[ ]?\d{0,4}\)|\(\d{0,4}\)|\d{0,4})` - 2nd capturing group. Matches either:
    * `(0` followed by 1 digit, an optional space, 0-4 digits and `)`,
    * 1-4 digits between brackets `()`, or
    * 0-4 digits.

* `((?:[\-\.\/ \t]{0,2}\d){3,8})` - Matches between 3-8 digits separated by up to two spaces, tabs or `-`, `.`, `/ ` characters.

* `(?:[\- \t]?(?:#|x|ext|extension)[\-\.\:\/]?[ \t]?(\d{1,4}))?` - Non-capturing group for extension numbers, similar to as described above.

* `$` - End of expression.

A demo showing the Regex in action is available [here](https://regex101.com/r/GDNQZr/1). Some matched and unmatched formats are included for reference.

**Discussion Points**:

1. This Regex is more rigid than the one proposed for Canadian/American phone number formats. For example, typically only 1 or 2 delimiter characters are accepted between digits where appropriate. Similarly, whitespace characters have been replaced with space and tab characters since it's unlikely to find, for example, a new line break in the middle of a phone number.

2. The Regex requires either the standard `+` character or `00` digits before the country code. This was done to prevent the Regex from being too aggressive in matching country codes. For example, `650-384-9911` would otherwise be grouped as `65 0 384 911` since `65` matches the country code for Singapore. A demo showing the Regex without this requirement is available [here](https://regex101.com/r/FQ8kz5/1) for comparison.

3. One possible solution/approach is to use the matched country code to determine the number of possible remaining digits. This [Wikipedia article](https://en.wikipedia.org/wiki/Telephone_numbers_in_Europe) is useful, but it only covers Europe.

**Comment by brandonlockhart** [comment]
Great job, @atol! Thanks for the thorough explanation, and I really like the demos. I will address your discussion points first:

For 1.,

> typically only 1 or 2 delimiter characters are accepted between digits where appropriate

I like the delimiters you used in the Canada/USA regex. And from the demos, it seems that examples like `1-234-567-8901` and `1 234 567 8901` will not match. This leads me to think that your point 3. is worth exploring; eg, if we identify the country code is 1, then we should match these formats

> Similarly, whitespace characters have been replaced with space and tab characters since it's unlikely to find, for example, a new line break in the middle of a phone number.

This seems fine to me, unless you see any problems with it.

For 2., I agree that we should not group `650-384-9911` as `65 0 384 911`, particularly since Singapore's format is `+65 XXXX-XXXX`. However, I'm concerned that requiring `+` or `00` to match the country code could be too strict. What do you think?

I like point 3., which seems similar to what Jiannan proposed in the last meeting. The main problem I see is that we would need to iterate over each country code and check if it matches the input, which would be slow. To improve the efficiency, we could perhaps prioritize country codes that we have already matched to try to not iterate over each code for each input. Run time aside, do you think an approach like this could work well and be more accurate than using your proposed regex? 

Also, I wonder if you looked at the `phonenumbers` library,  and if they solved this problem? On there wiki they state this though
``` python
z = phonenumbers.parse("02081234567", None)  # no region, no + => unparseable
```
so we might be a bit more ambitious than they are. 

It seems like the three-digit central office code, and a four-digit station code, are not captured in different groups as they were in the Canada/USA regex. Is this correct? And if so, do you think this is a problem?

Lastly, I would like to float the idea of validating a telephone number for a particular country, e.g., `validate_country("1-123-456-789", country="Canada")` (similar to the [phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) library). Therefore, we would need a regex for each country.

**Comment by brandonlockhart** [comment]
> There seems to be a trade-off in trying to be flexible enough to capture a variety of formats and being structured enough to separate out the different components.

I agree. I think in some cases it must be impossible to map a string of numbers to a unique, valid phone number.

I wonder if we could make these assumptions for `clean_phone`:
1. If the column contains phone numbers from multiple countries, each phone number has a country code
2. If the column contains phone numbers from a single country, the user can set a parameter `country` (perhaps default "USA"), and the phone numbers do not require a country code

For example, `clean_phone(df, "phone_number)`, `clean_phone(df, "phone_number, country="all")`, `clean_phone(df, "phone_number, country="UK")` would match USA/Canada, international, and UK formats respectively. Also, it looks like the phonenumbers library has defined [regexes](https://github.com/daviddrysdale/python-phonenumbers/blob/fba10707272dbdf2402ff12dadcb3ae54666d796/resources/PhoneNumberMetadata.xml) for each country. Please let me know any opinions.

**Comment by jnwang** [comment]
Great job @atol and @brandonlockhart! I don’t how much effort it will need to support all countries. If it requires a lot of effort, I suggest we do it step by step (like plot(df) function, we are still adding new features to it). We can commit what we have so far and optimize it as we see more use cases.
