### ISSUE TITLE
plot(df): xtics need to be optimized for numerical attributes 

### ISSUE THREAD

**Issue by jnwang** [sfu-db/dataprep#38]
I was doing plot(df) on the example data and found that the xtics of many numerical attributes are not carefully set. Below I compared the xtics of tableau (left) and dataprep (right). Apparently, tableau looks better. This is not a high-priority, but worth considering in the future release. 

<img width="641" alt="Screen Shot 2019-12-18 at 10 05 45 PM" src="https://user-images.githubusercontent.com/1028970/71149200-b28afc80-21e2-11ea-9516-4adf13ddd189.png">

**Comment by brandonlockhart** [comment]
@jnwang could you please give reasons for your statement "Apparently, tableau looks better". With our current method the user can easily infer the bin endpoints, which I think is harder to do in Tableau. But perhaps the user just wants an overall idea of the distribution, in which case my last sentence is less important. The user can also use the tooltip to get the exact bins. We can change the ticks, we would just need to define the rules. I think Tableau looks cleaner because they use less ticks and are rounding.
![image](https://user-images.githubusercontent.com/25874021/71648935-4bc81180-2cbf-11ea-8355-a2080762e909.png)

**Comment by jnwang** [comment]
What you understood is exactly what I thought. 

There are a few open-source tools that can generate xtics automatically. Maybe we can derive some rules from them.

http://gnuplot.sourceforge.net/docs_4.2/node295.html
https://data-voyager.gitbook.io/voyager/visualizing-data/univariate-summaries

**Comment by jinglinpeng** [comment]
I have a quick thought. If x tic values is in the form of 5*n*10^k, where n is a non-negative integer and k is any integer (could be negative),  then it looks good. Examples including 5, 10, 15 and 0.5, 1,.0, 1.5. Maybe we could have a test on tableau see whether there is any other case. If it is, we could summarize some other rules.

**Comment by jnwang** [comment]
It looks like a good idea. Please have a test.

**Comment by brandonlockhart** [comment]
From discussion with Jinglin, we think that the purpose of the x tics is to give a general idea of the range of values in the histogram's distribution. With that in mind, we have defined some rules:
1. Always show 5 tics (5 is a modifiable parameter)
2. The smallest and largest tics are the smallest and largest values of the distribution respectively
3. Other ticks are spread equally in that range
4. Round the tic values as much as possible (might encounter problems here)
5. Use K, M, B for thousand, million and billion as in Tableau, and scientific notation for very large and very small values
![Screenshot at 2020-01-08 13:38:42](https://user-images.githubusercontent.com/25874021/72018273-35b8d480-321c-11ea-853b-35d884d381b9.png)
We will try to emulate Tableau

**Comment by jnwang** [comment]
It's good enough for now. Thank you!
