### ISSUE TITLE
Connector: Improve the .info Function

### ISSUE THREAD

**Issue by nick-zrymiak** [sfu-db/dataprep#386]
## Summary
The .info function should tell the user what are the parameters and how to use them.

## Design-level Explanation Actions
NA

## Design-level Explanation

- [ ] Create output for show_schema.
- [ ] Remove show table. The info function will display table names also so show table is redundant.
- [ ] Display the response in a browser to make the information more readable and so users can easily view all table names.
- [ ] Show an example of Connector and query for each table including all required query list parameters and universal 
        parameters applicable to each table.
![UI](https://user-images.githubusercontent.com/35017006/95701915-b4093380-0bff-11eb-801e-5e5f7711a8c6.png)

## Additional Tasks

- [x] This task is put into a correct pipeline (Development Backlog or In Progress).
- [x] The label of this task is setting correctly.
- [x] The issue is assigned to the correct person.
- [x] The issue is linked to related Epic.

- [ ] The documentation is changed accordingly.
- [ ] Tests are added accordingly.

**Comment by peiwangdb** [comment]
Very elegant and comprehensive design @nick-zrymiak  ! (I saw a duplicate "Design-level Explanation" header.)

Below are my thoughts on the items you listed:

For the show_schema, I was thinking: the purpose of show_schema is to give users expectations on what attributes will be returned. So that can be a part of the info as well, let me know how do you think :)

For the show_table, this HTML design limits the number of APIs to display so the user won't be able to see all the tables. My question is, is "more_tables" clickable?

"Display the response in a browser to make the information more readable and so users can easily view all table names."
Could you explain or prototype more for this idea? Is this what is you included in the picture or is it something else?

and I saw the example code of Connector(...), if this info is called the current way, at this time, the user should have already initialized a connector,  so I am thinking if we should make .info independent from the connector class (and it only relies on config files).

It is a much better design compared with the previous one, great job @nick-zrymiak ! and let me know your thoughts!

**Comment by nick-zrymiak** [comment]
![image](https://user-images.githubusercontent.com/35017006/95692364-10595c80-0bda-11eb-844d-78b32ca31fff.png)
![image](https://user-images.githubusercontent.com/35017006/95692372-164f3d80-0bda-11eb-9281-cc613c4b68b6.png)

Thank you again, Penny. Really appreciate the input!

**Comment by peiwangdb** [comment]
Thanks for the detailed thoughts @nick-zrymiak !

Here is my thought for the show_schema for your reference:
I assume that using the df.dtypes reads the attribute name and type, the information is extracted from the returned df. 
While the current show_schema reads the information from the config file and does not need a successfully returned df, 
the user can assess if the returned info will meet their needs. 
And can we assume all the users know df.dtypes?

The show_tables plan sounds good to me.

**Comment by nick-zrymiak** [comment]
Ooo that's true. Ok we'll keep the show_schema function :)

**Another minor suggestion: change API_name to website_name.**

So for the image of the response in show browser I added to the description, instead of where API_name is right now, the actual response will show musixmatch or spotify or whatever the actual name of the website is. I will update the issue description with that change for now though just to make it more clear. Thanks @peiwangdb!

**Comment by peiwangdb** [comment]
Thanks @nick-zrymiak ! 
It sounds great!
In the case we keep the show_schema, don't forget to design a nice and aligned look for it too:)

**Comment by nick-zrymiak** [comment]
![Q](https://user-images.githubusercontent.com/35017006/95855554-7397db80-0d0d-11eb-81ff-471cf41ab46c.png)

Please let me know your thoughts!
