### ISSUE TITLE
The progress bar in dataprep.eda didn't show the progress.

### ISSUE THREAD

**Issue by zhangk1551** [sfu-db/dataprep#475]
**Describe the bug**
As we see in the screenshot, the progress bar in `dataprep.eda` didn't show the progress. I also tried to run tqdm directly, and the progress bar worked well, so it's probably not an installation problem.

**To Reproduce**
The code is from [this notebook](https://github.com/sfu-db/bigdata-cmpt733/blob/master/Assignments/A1/A1-1.ipynb) and here are [the data](https://github.com/sfu-db/bigdata-cmpt733/blob/88d5781914c194be3f297a66132892902efc80a5/Assignments/A1/faculty_table.csv)

**Expected behavior**
The progress should show after we run the code.

**Screenshots**
![image](https://user-images.githubusercontent.com/26733898/104797291-ed050580-57f7-11eb-8b85-a33b68ae8080.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. Chrome]
 - Platform [Jupyter Lab]
 - Python Version [3.9.1]
 - Dataprep Version [0.2.15]
 - tqdm [4.56.0]

**Comment by dovahcrow** [comment]
@zhangk1551 I feel like this is due to the incorrect installation of ipywidget: the progress bar shown in your example is the console version, not the jupyter version. Maybe you can take a look at the installation guide of ipywidget to see if you've installed it correctly. https://ipywidgets.readthedocs.io/en/stable/user_install.html

**Comment by zhangk1551** [comment]
I've installed ipywidget. After I reinstalled jupyterlab-widgets, it worked. Thank you :)
