### ISSUE TITLE
clean: validate_country() cannot work as expected

### ISSUE THREAD

**Issue by yuzhenmao** [sfu-db/dataprep#567]
**Describe the bug**
when I test validate_country, I found it treated string number as country names: (df['str'] is string type)
![image](https://user-images.githubusercontent.com/57878927/113986201-8edc4180-987f-11eb-9f46-b703dc078e8b.png)

**Expected behavior**
It should return "false false false".

**Comment by brandonlockhart** [comment]
Thanks @yuzhenmao for creating this issue and @ryanwdale for your detailed comment. I like both of the proposed solutions. I think letting`input_format` accept a string and a tuple is a good idea since it gives the user more control over the validation process. However, it could be easier to just type `exclude_numeric=True` rather than `input_format=("name", "official", "alpha-2", "alpha-3")`. I like the tuple solution a bit better since it's more powerful and we wouldn't introduce another parameter, but I also like `exclude_numeric`.
