### ISSUE TITLE
EDA create_report

### ISSUE THREAD

**Issue by akashg116414** [sfu-db/dataprep#675]
cannot be used anywhere because of very very high memory consumption, renders it highly unusable. though having great features for example for a 250 mb dataset the library consumes 3.5 to 4 gb  of a memory space causing a deadlock in machine.
can it be fixed and tuned for optimal memory utilization

**Comment by jnwang** [comment]
Hi @akashg116414 , would you mind providing more details so that we can reproduce this issue? Thank you! 

@jinglinpeng @dovahcrow

**Comment by akashg116414** [comment]
https://drive.google.com/file/d/1BbrvQjKgbWEpaeqlRQ_4LgiDFHKdXADJ/view?usp=sharing

please find the attachment of dataset link and with same dataset i got above mention bug while using eda.create_report().

**Comment by jinglinpeng** [comment]
Hi @akashg116414  Thanks for sharing the data! We'll take a look!

**Comment by akashg116414** [comment]
Okay, Any update. by when this will resolved.

**Comment by jinglinpeng** [comment]
Hi @akashg116414 , I tested the data you provided on a MAC laptop. The report was created in around 3 mins and the peak memory is 2.5 GB. In the meantime, loading df to Pandas itself will spend 600 MB. 

FYI, this is the script I used to test the peak memory:
```python
import tracemalloc
import pandas as pd
from dataprep.eda import create_report

if __name__ == "__main__":
    tracemalloc.start()
    df = pd.read_csv("fraudTrain.csv")
    create_report(df).save("report")
    current, peak = tracemalloc.get_traced_memory()
    print(f"Peak was {peak / 10**6}MB")
    tracemalloc.stop()
```

The memory consumption itself is a challenging problem in Python, where usually lots of data copies will happen, such as in Pandas. For dataprep, it spends more memory than Pandas because it needs to preprocess the dataframe and cache some results, in order to  handle different data types and speed up following computations. For a comparison, I also tested Pandas-Profiling, it spends around 6 mins, and has a peak memory 4 GB.

We'll optimize the memory consumption gradually since it's challenging. For now, here are some suggestions that may be useful:
1. Use `plot`, `plot_correlation` and `plot_missing`. In my test, the peak memory for each of them is around 1.7 GB, which is half of the `create_report`.
2. Use a sample of the data.
3. Use a subset of the columns.
