### ISSUE TITLE
interactions not plotting everything in scatter plot

### ISSUE THREAD

**Issue by jasjyotsinghjaswal** [sfu-db/dataprep#687]
Hi ,
Dataprep works great except for Interactions wherein I have checked against multiple attributes and I see scatterplots are not generated for all range of values and I have done comparisons viz-a-viz against plots generated from DTale and they cover the entire range of values but Dataprep Interactions is only covering a subset

**Comment by jinglinpeng** [comment]
Hi @jasjyotsinghjaswal , thanks a lot for the issue! This issue was fixed by #688 . By default we will use sampling for `scatter` plot to avoid the issue with too many points. Now you can set `scatter.sample_rate = 1.0` to avoid sampling if you want. Could you please update the DataPrep to the develop version by `pip install -U git+https://github.com/sfu-db/dataprep.git@develop`, and then try to set `scatter.sample_size` or `scatter.sample_rate`? The following code shows an example.

```python
from dataprep.eda import create_report
from dataprep.datasets import load_dataset
import pandas as pd
df = load_dataset("adult")
create_report(df, config = {"scatter.sample_rate": 0.1})
# or create_report(df, config = {"scatter.sample_size": 2000})
```
